### ISSUE TITLE
can't "npm install"

### ISSUE THREAD

**Issue by THEJJDEV** [TeeraphatCH15224/Teeraphat_CH-Manager#1]
`npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/TeeraphatCH15224/SuperWeir-Joox.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.`

**Comment by TeeraphatCH15224** [comment]
แก้แล้วนะครับ

**Comment by THEJJDEV** [comment]
ขอบคุณครับ
